src/App/Form/TwitterType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Regex;

/**
 * Class TwitterType.
 */
class TwitterType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'text';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'constraints' => [
                new Regex([
                    'pattern' => '/^[A-Za-z0-9_]{1,15}$/',
                    'message' => 'Usuario de twitter inválido.',
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'twitter';
    }
}

src/App/Resources/views/_partials/banner.html.twig
<!-- Teaser -->
<div class="banner" id="home">
    <div class="banner_bg" data-stellar-background-ratio="0.2" style="background-image: url('/images/bg_banner.jpg');"></div>
    <div class="row">
        <div class="colums small-12 medium-12-large-12">
            <div class="center-content">
                <!-- Site title -->
                <div class="logo">
                    <h1 id="site-title">PHP day 2015</h1>
                </div>

                <!-- Site Description -->
                <div class="sub-logo">
                    <h2 id="site-description">{{ "site_description"|trans }}</h2>
                </div>

                <!-- Event Info -->
                <div class="event-info">
                    <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-4">
                        <li><i class="fa fa-map-marker "></i>Montevideo, Uruguay</li>
                        <li><i class="fa fa-calendar"></i>{{ '8 august 2015'|localizeddate('medium', 'none', app.locale) }}</li>
                        <li><i class="fa fa-microphone"></i>23 {{ "speakers"|trans }}</li>
                        <li><i class="fa fa-ticket"></i>{{ "free_ticket"|trans }}</li>
                    </ul>
                </div>

                <h1>{{ 'banner_motto'|trans }}</h1>

                <h2>{{- "banner_description"|trans|nl2br|nonl -}}</h2>

                <!-- Social Links -->
                <div class="row">
                    <div class="large-6 small-centered columns">
                        <div class="event-social">
                            <ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-1">
                                <li>
                                    <a href="https://twitter.com/phpdayuy"> <i class="fa fa-twitter"></i>Twitter</a>
                                </li>
{#
                                <li>
                                    <a href="">
                                        <i class="fa fa-facebook"></i>Facebook
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <i class="fa fa-google-plus"></i>Google+
                                    </a>
                                </li>
#}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/banner_small.html.twig
<div class="mini_header">
    <div class="mini_header_bg" data-stellar-background-ratio="0.2" style="background-image: url('/images/bg_banner.jpg');"></div>
    <div class="row">
        <div class="columns small-12 medium-12 large-12">
            <!-- Site title -->
            <div class="logo">
                <h1 id="site-title">PHP day 2015</h1>
            </div>

            <!-- Site description -->
            <div class="sub-logo">
                <h2 id="site-description">{{ "site_description"|trans }}</h2>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/cfp.html.twig
<div class="row">
    <h3>{{ "cfp.title"|trans }}</h3>

    <p>{{ 'cfp.description.header'|trans|nl2br }}</p>

    <!-- View all Speakers Button -->
    <div class="view-all-speakers">
        <a href="{{ path('cfp') }}" class="btn-default">{{ 'submit_talk'|trans }}</a>
    </div>

</div>

src/App/Resources/views/_partials/footer.html.twig
<div class="footer">
    <div class="footer_bg" data-stellar-background-ratio="0.2" style="background-image: url('/images/bg_buytikets.png');"></div>
    <div class="footer_widgets">
        <div class="row">
            <div class="columns small-12 medium-4 large-4">
                <!-- About us -->
                <aside id="Widget-text1" class="widget widget_text">
                    <h3>{{ 'footer.aboutus' | trans }}</h3>

                    <div class="textwidget">
                        <p>{{ 'footer.wethepeople' | trans }}</p>

                        <p>{{ 'footer.motto' | trans }}</p>
                    </div>
                </aside>
            </div>

            {% if section_bag.isSectionEnabled("blog_posts") %}
            <!-- Popular posts -->
            <div class="columns small-12 medium-4 large-4">
                <aside id="populat-1" class="widget  widget_recent_entries">
                    <h3>Blog</h3>

                    <div class="">
                        <ul id="menu-1" class="menu">
                            <!-- First Post -->
                            <li>
                                <a href="">Lorem ipsum dolor sit amet, consectetur adipiscing</a>

                                <div class="post_meta">
                                    <span class="date">28/03/2014</span>
                                    <span class="category">News & Announcements</span>
                                </div>
                            </li>

                            <!-- Second Post -->
                            <li>
                                <a href="">Vestibulum in augue a enim dictum fermentum.</a>

                                <div class="post_meta">
                                    <span class="date">26/03/2014</span>
                                    <span class="category">Sponsors</span>
                                </div>
                            </li>

                            <!-- Third post -->
                            <li>
                                <a href="">Morbi luctus enim sit amet odio pharetra, ac tincidunt eros dictum</a>

                                <div class="post_meta">
                                    <span class="date">28/03/2014</span>
                                    <span class="category">Schedule Updates</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            {% endif %}

            {% if section_bag.isSectionEnabled("media_gallery") %}
            <!-- Gallery Widget -->
            <div class="columns small-12 medium-4 large-4">
                <aside id="gallery-1" class="widget widget_gallery">
                    <h3>Fotos</h3>

                    <div class="gallery_slider">
                        <div id="owl-gallery" class="owl-carousel owl-theme">
                            <!-- First Image -->
                            <div class="item">
                                <img src="images/gallery_01.jpg" width="600" height="240" alt="image">
                            </div>

                            <!-- Second Image -->
                            <div class="item">
                                <img src="images/gallery_02.jpg" width="600" height="240" alt="image">
                            </div>

                            <!-- Third Image -->
                            <div class="item">
                                <img src="images/gallery_03.jpg" width="600" height="240" alt="image">
                            </div>
                        </div>

                        <!-- Pagination -->
                        <div class="customNavigation">
                            <a class="btn prev-gallery"><i class="fa fa-angle-left"></i></a>
                            <a class="btn next-gallery"><i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                </aside>
            </div>
            {% endif %}
        </div>
    </div>

    <!-- Copyright -->
    <div class="footer_copyright">
        <div class="row">
            <div class="columns small-12 medium-5 large-5">
                <a href="mailto:info@phpday.uy">info@phpday.uy</a>
            </div>
            <div class="columns small-12 medium-7 large-7">
                <ul class="inline-list right">
                    <li><a href="{{ path('code_conduct') }}">{{ 'footer.codeofconduct' | trans }}</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/form_theming.html.twig
{% use "form_div_layout.html.twig" %}

{%- block form_row -%}
    <div>
        <label {% if form.vars.errors|length > 0 %}class="error"{% endif %}>
            {%- if label is empty -%}
                {%- if label_format is not empty -%}
                    {% set label = label_format|replace({
                    '%name%': name,
                    '%id%': id,
                    }) %}
                {%- else -%}
                    {% set label = name|humanize %}
                {%- endif -%}
            {%- endif -%}

            {{- label|trans -}}

            {%- if form.vars.noted|default(false) -%}
                *
            {%- endif -%}
            {%- if not form.vars.required -%}
                <small> ({{ 'form.field.optional'|trans }})</small>
            {%- endif -%}

            {{- form_widget(form) -}}
        </label>
        {{- form_errors(form) -}}
    </div>
{%- endblock form_row -%}


{% block twitter_widget %}
    <div class="row collapse">
        <div class="small-2 columns">
            <span class="prefix">@</span>
        </div>
        <div class="small-10 columns">
            {{ form_widget(form) }}
        </div>
    </div>
{% endblock %}

{# errors #}

{%- block form_errors -%}
    {% if errors|length > 0 %}
        {%- if form.parent -%}
            <small class="error">
                {%- for error in errors -%}
                    {{ error.message }}<br/>
                {%- endfor -%}
            </small>
        {%- else -%}
            <div class="alert-box error">
                {%- for error in errors -%}
                    {{ error.message }}
                {%- endfor -%}
            </div>
        {%- endif -%}
    {%- endif -%}
{%- endblock -%}

src/App/Resources/views/_partials/latest_posts.html.twig
<!-- Latest Posts -->
<div class="widget_latestposts_homepage widget-content" id="latestposts_homepage">
    <div class="row">
        <div class="columns small-12 medium-12 large-12">
            <div class="center-content">
                <h2>Latest Posts</h2>
            </div>
            <div class="">
                <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-4">
                    <!-- First Post -->
                    <li>
                        <div class="featuredimg">
                            <a href="single-post.html">
                                <img src="images/thumb_blog_post_01.jpg" width="600" height="173" alt="avatar">
                            </a>
                        </div>
                        <div class="post_title">
                            <a href="single-post.html">Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue.</a>
                        </div>
                        <div class="post_meta">
                            <span class="date">28/30/2014</span>
                            <span class="category">News & Announcements</span>
                        </div>
                        <div class="post_excerpt">
                            Suspendisse mauris. Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula. Integer adipiscing risus a sem...
                        </div>
                    </li>

                    <!-- Second Post -->
                    <li>
                        <div class="featuredimg">
                            <a href="single-post.html">
                                <img src="images/thumb_blog_post_02.jpg" width="600" height="173" alt="avatar">
                            </a>
                        </div>
                        <div class="post_title">
                            <a href="single-post.html">Ultrices nulla quis nibh. Quisque a lectus donec consectetuer.</a>
                        </div>
                        <div class="post_meta">
                            <span class="date">28/30/2014</span>
                            <span class="category">News & Announcements</span>
                        </div>
                        <div class="post_excerpt">
                            Nunc sem lacus, accumsan quis, faucibus non, congue vel, arcu. Ut scelerisque hendrerit tellus integer sagittis vivamus...
                        </div>
                    </li>

                    <!-- Third Post -->
                    <li>
                        <div class="featuredimg">
                            <a href="single-post.html">
                                <img src="images/thumb_blog_post_03.jpg" width="600" height="173" alt="avatar">
                            </a>
                        </div>
                        <div class="post_title">
                            <a href="single-post.html">Sed egestas, ante et vulputate volutpat, eros pede semper est.</a>
                        </div>
                        <div class="post_meta">
                            <span class="date">28/30/2014</span>
                            <span class="category">News & Announcements</span>
                        </div>
                        <div class="post_excerpt">
                            Convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed augue. Integer eu magna...
                        </div>
                    </li>

                    <!-- Forth Post -->
                    <li>
                        <div class="featuredimg">
                            <a href="single-post.html">
                                <img src="images/thumb_blog_post_04.jpg" width="600" height="173" alt="avatar">
                            </a>
                        </div>
                        <div class="post_title">
                            <a href="single-post.html">Morbi interdum mollis sapien. Sed ac risus phasellus lacinia.</a>
                        </div>
                        <div class="post_meta">
                            <span class="date">28/30/2014</span>
                            <span class="category">News & Announcements</span>
                        </div>
                        <div class="post_excerpt">
                            Condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus nunc...
                        </div>
                    </li>
                </ul>
            </div>
            <div class="visit-our-blog center-content">
                <a href="list-posts.html" class="btn-default">VISIT OUR BLOG</a>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/mailing_list.html.twig
<!-- Mailing List -->
<div class="mailinglist widget-content">
    <div class="mailinglist_bg" data-stellar-background-ratio="0.2" style="background-image: url('/images/bg_mailinglist.jpg');"></div>
    <div class="row">
        <div class="columns small-12 medium-12 large-4 envelope">
            <div class="join">{{ 'subscription.title'|trans }}:</div>
        </div>
        <div class="columns small-12 medium-12 large-8">
            <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
                <form action="//phpmvd.us10.list-manage.com/subscribe/post?u=8e27e1aff64f1b783c10f4448&amp;id=dfe9b6f1e4" method="post" target="_blank">
                    <input type="text" value="" name="NAME" placeholder="{{ 'subscription.name_helper'|trans }}">
                    <input type="email" value="" name="EMAIL" placeholder="{{ 'subscription.email_helper'|trans }}">
                    <button class="btn-default" type="submit">{{ 'subscription.button'|trans }}</button>

                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;">
                        <input type="text" name="b_8e27e1aff64f1b783c10f4448_dfe9b6f1e4" tabindex="-1" value="">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/map.html.twig
<!-- Contact us / Map -->
<div class="maps" id="location">
    <div id="js-map"></div>
    <div class="map-location">
        <h2>{{ 'map.title'|trans }}</h2>
        <ul itemscope="" itemtype="http://schema.org/PostalAddress">
            <li class="title">{{ 'map.street_address'|trans }}</li>
            <li itemprop="address">Av. Rivera 3729 bis, Montevideo, UY</li>
            <li class="title">{{ 'map.email_address'|trans }}</li>
            <li itemprop="email">info@phpday.uy</li>
{#
            <li class="title">Telephone Number</li>
            <li itemprop="telephone">(514) 000-0000</li>
#}
        </ul>
    </div>
</div>
<script type="text/javascript">var wplMap = {Lat : -34.899377, Long: -56.142004}, wplMarker = {Lat : -34.899377, Long: -56.132004}</script>

src/App/Resources/views/_partials/navbar.html.twig
<div class="main_menu navbar-fixed">
    <div class="row">
        <div class="columns small-12 medium-12 large-12">
            <div class="mb">
                <div class="navmobile"><a href=""></a></div>
                <ul class="nav-menu">
                    <li class="menuItem"><a href="{{ path('homepage') }}#home">{{ 'homepage'|trans }}</a></li>

                    {% for section in ["speakers","schedule","sponsors"] %}
                        {% if section_bag.isSectionEnabled(section) %}
                            {# Item de la sección, solo si está habilitado#}
                            <li class="menuItem"><a href="{{ path('homepage') }}#{{ section }}">{{ section|trans }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <li class="menuItem"><a href="{{ path('homepage') }}#location">{{ "location"|trans }}</a></li>

                    <!-- <li class="menuItem"><a href="#pricing">Precio</a></li> -->
                    {% if section_bag.isSectionEnabled('registration') %}
                        <li class="register"><a href="" data-reveal-id="RegisterModal">{{ 'register'|trans }}</a></li>
                    {% else %}
                        <li class="soldout">{{ 'soldout'|trans }}</li>
                    {% endif %}

                    {% for _lang in ["en", "es"] %}
                        {% if _lang != app.locale %}
                            <li class="language">
                                <a href="{{ path('homepage', {"_locale": _lang}) }}">{{ _lang|upper }}</a></li>
                        {% endif %}
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</div>

src/App/Resources/views/_partials/schedule.html.twig
{% macro charla(key, talk) %}
    {%- spaceless -%}
        <a href="" data-reveal-id="talk-{{ key }}" class="event-title center-content">
            {{- talk.title -}}
        </a>

        <div id="talk-{{ key }}" class="reveal-modal medium event-detail" data-reveal>
            <div class="row">
                <div class="columns small-9">
                    <h3>{{ talk.title }}</h3>

                    {% if talk.speaker is not empty %}
                        <div>
                            <i class="fa fa-user"></i> {{ talk.speaker|speaker_name -}}
                        </div>
                    {% endif %}

                    {% if talk.level is not empty %}
                        <div>
                            <i class="fa fa-university"></i> {{ talk.level|trans -}}
                        </div>
                    {% endif %}

                    {% if talk.link_deck is not empty %}
                        <div>
                            <i class="fa fa-file-powerpoint-o"></i> <a href="{{ talk.link_deck }}" target="_blank">{{ "talk_slides"|trans }}</a>
                        </div>
                    {% endif %}

                    {% if talk.link_code is not empty %}
                        <div>
                            <i class="fa fa-file-code-o"></i> <a href="{{ talk.link_code }}" target="_blank">{{ "talk_code"|trans }}</a>
                        </div>
                    {% endif %}
                </div>
                {% if talk.speaker is not empty %}
                    <div class="columns small-3 text-right">
                        {% for speaker in talk.speaker %}
                            <img src="{{ speaker|speaker_avatar }}" class="avatar-small radius" alt="avatar" data-tooltip title="{{- speaker|speaker_name -}}">
                        {% else %}
                            <img src="{{ talk.speaker|speaker_avatar }}" class="avatar radius" alt="avatar" data-tooltip title="{{- talk.speaker|speaker_name -}}">
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="row event-description">
                <p class="column small-12 text-justify">{{ talk.description }}</p>
            </div>
            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>
    {%- endspaceless -%}
{% endmacro %}


<!-- Schedule -->
<div class="schedule widget-content" id="schedule">
    <div class="row">
        <div class="columns small-12 medium-12 large-12">
            <div class="center-content">
                <h2>{{ "schedule"|trans }}</h2>

                <!-- <div data-alert class="alert-box radius warning">{{ "schedule_tbc"|trans }}</div> -->
            </div>

            <table role="grid" class="event-grid">
                <thead>

                    <tr>
                        <th width="12%" id="schedule-times" class="center-content">
                            <i class="fa fa-clock-o"></i>
                        </th>

                        {% set column_width = (100 - 12) / (schedule_info.rooms|length) %}
                        {% for room in schedule_info.rooms %}
                            <th width="{{ column_width }}%" class="center-content">{{ room.room_name }}</th>
                        {% endfor %}
                    </tr>

                </thead>
                <tbody>
                    {% for time, schedule in schedule_info.schedules %}
                        <tr>
                            {% if 'rooms' != schedule %}
                                <th headers="schedule-times" class="event-time center-content">{{ time }}</th>
                            {% endif %}

                            {% for content in schedule if content.blocks is not defined %}

                                {% if content.talk is defined %}

                                    {# Hay una charla definida para este horario en esta sala #}
                                    <td>{{- _self.charla(content.talk, schedule_info.talks[content.talk]) -}}</td>

                                {% endif %}

                            {% else %}
                                {% if "rooms" == schedule %}
                                    <th>&nbsp;</th>
                                    {% for room in schedule_info.rooms %}
                                        <th class="center-content">{{ room.room_name }}</th>
                                    {% endfor %}
                                {% else %}
                                    {# texto de acreditacion o break #}
                                    <td colspan="{{ schedule_info.rooms|length }}" class="center-content">
                                        <strong>{{- schedule|trans({}, 'talks') -}}</strong>
                                    </td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

src/App/Resources/views/_partials/speaker_list.html.twig
<div class="row">
    <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-4">
        {% for key, speaker in speakers %}
            <!-- First Speacker -->
            <li>
                <div class="avatar">
                    <img src="{{ speaker.avatar }}" width="220" height="220" alt="Avatar1">
                    <!-- Speaker media links -->
                    <div class="social">
                        {% if speaker.url is defined %}
                            <!-- Speaker profile / blog url -->
                            <a href="{{ speaker.url }}" target="_blank">
                                <i class="fa fa-user"></i>
                            </a>
                        {% endif %}

                        {%- if speaker.twitter is defined and speaker.twitter is not empty -%}
                            <!-- Speaker Twitter URL -->
                            <a href="https://twitter.com/{{ speaker.twitter }}" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                        {%- endif -%}

                        {%- if speaker.linkedin is defined and speaker.linkedin is not empty -%}
                            <!-- Speaker Linkedin URL -->
                            <a href="{{ speaker.linkedin }}" target="_blank">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        {%- endif -%}

                        &nbsp;

                        {%- if speaker.bio is defined and speaker.bio is not empty -%}
                            {# Speaker Bio #}
                            <a href="" data-reveal-id="SpeakerBioModal{{ key }}">
                                <i class="fa fa-user"></i>
                            </a>
                        {%- endif -%}
                    </div>
                </div>
                <div class="name">
                    {% if speaker.bio is defined and speaker.bio is not empty %}
                        <a href="" data-reveal-id="SpeakerBioModal{{ key }}">{{ speaker.name }}</a>
                    {% else %}
                        <a href="" target="_blank">{{ speaker.name }}</a>
                    {% endif %}
                </div>

                {# Modal dialog for Speaker Bio #}
                <div id="SpeakerBioModal{{ key }}" class="reveal-modal small" data-reveal>
                    <div class="row">
                        <h4 class="columns small-12">{{ speaker.name }}</h4>
                    </div>

                    <div class="row">
                        <div class="large-12 columns">
                            <p>{{ speaker.bio }}</p>
                        </div>
                    </div>
                    <a class="close-reveal-modal">&#215;</a>
                </div>


                {% if speaker.company is defined %}
                    <div class="company">
                        <a href="{{ speaker.company.url }}" target="_blank">{{ speaker.company.name }}</a>
                    </div>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>
{#
<!-- View all Speakers Button -->
<div class="view-all-speakers">
    <a href="speakers.html" class="btn-default">{{ "speaker_list.view_all"|trans }}</a>
</div>
#}

src/App/Resources/views/_partials/speakers.html.twig
<!-- Speakers -->
<div class="speakers widget-content" id="speakers">
    <div class="row">
        <div class="columns small-12 medium-12 large-12">
            <div class="center-content">
                <h2>{{ "speakers"|trans }}</h2>

                {% if speakers is not empty %}
                    {% include "_partials/speaker_list.html.twig" %}
                {% endif %}

                {% if section_bag.isSectionEnabled("cfp") %}
                    {% include "_partials/cfp.html.twig" %}
                {% endif %}
            </div>
        </div>
    </div>
</div>